version: '3.3'
services:
    analytic:
      image: analytic
      container_name: analytic
      build:
        context: .
        dockerfile: Dockerfile
      ports:
       - 8080:80
      volumes:
       - .:/var/www